### ISSUE TITLE
Fetch code based on "Markers" rather than Line Numbers

### ISSUE THREAD

**Issue by samhita-alla** [saucelabs/docusaurus-theme-github-codeblock#10]
Hi All,

Is there a possibility to include markers rather than line numbers while referencing the code snippets? For instance, here's an example code snippet:

```
# start_hello_function

def say_hello() -> str:
    return "hello world"

# end_hello_function
```

Here, `start_hello_function` and `end_hello_function` are the markers.

When this feature is included, we need not worry when there's additional code added as the code lying within the markers gets picked up when the changes are pushed.

Let me know what you think of it. 
Thanks in advance!

**Comment by christian-bromann** [comment]
Hey @samhita-alla , thanks for filing the issue.

> When this feature is included, we need not worry when there's additional code added as the code lying within the markers gets picked up when the changes are pushed.

I am not sure if using markers is a good idea because it is extra code just to accommodate an example integration. I suggest to use GitHub urls with sha values, e.g. `https://github.com/saucelabs/docusaurus-theme-github-codeblock/blob/50d7729cd80cbdf3a56b1829a69328152265938f/package.json#L6-L8`. This would solve your problem without having to modify the example.
